import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  real,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

/**
 * Blueprints.md §10 "Data shapes" / solution.md §11.3 "What the database
 * holds". Smaller than expected on purpose — snapshot payloads live in
 * WordPress, not here (solution.md §3): content stays with the site, and
 * rollback survives a Node outage.
 *
 * solution.md §17: "site_id must be part of every cache key, storage path
 * and index — post ID 42 exists on every WordPress site." Every table below
 * that holds site-scoped data carries `siteId` and indexes it, not as an
 * afterthought.
 */

export const sites = pgTable('sites', {
  id: uuid('id').primaryKey().defaultRandom(),
  // Unguessable, not sequential (Blueprints.md §10) — generated by the
  // application at insert time, not a DB sequence.
  slug: text('slug').notNull().unique(),
  url: text('url').notNull(),
  generationDefault: text('generation_default', { enum: ['v4', 'v3', 'legacy'] }),
  environment: text('environment', { enum: ['sandbox', 'client'] }).notNull(),
  pluginVersion: text('plugin_version'),
  minSupportedPluginVersion: text('min_supported_plugin_version'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const grants = pgTable(
  'grants',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    oauthSubject: text('oauth_subject').notNull(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    scopes: jsonb('scopes').$type<string[]>().notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // solution.md §9.2: credentials resolved from (subject, site) with no
    // fallback — this is the uniqueness that makes that lookup meaningful.
    uniqueIndex('grants_subject_site_idx').on(table.oauthSubject, table.siteId),
    index('grants_site_id_idx').on(table.siteId),
  ],
);

export const credentials = pgTable(
  'credentials',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    // Envelope encryption, per-site DEK (solution.md §9.4) — the KEK lives
    // outside this database entirely, in a KMS the renderer has no grant to.
    encryptedDek: text('encrypted_dek').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    rotatedAt: timestamp('rotated_at', { withTimezone: true }),
  },
  (table) => [index('credentials_site_id_idx').on(table.siteId)],
);

export const ledgerIndex = pgTable(
  'ledger_index',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    subject: text('subject').notNull(),
    tool: text('tool').notNull(),
    // Allowlisted in, never denylisted out (Blueprints.md §10).
    redactedArgs: jsonb('redacted_args').notNull(),
    correlationId: text('correlation_id').notNull(),
    timestamp: timestamp('timestamp', { withTimezone: true }).notNull().defaultNow(),
    // Points at the WordPress-side snapshot; not a local FK, the payload
    // itself never lives here.
    snapshotPointer: text('snapshot_pointer'),
    rawRatio: real('raw_ratio'),
    nativeness: real('nativeness'),
    approvalTokenRef: uuid('approval_token_ref'),
  },
  (table) => [
    index('ledger_index_site_id_idx').on(table.siteId),
    index('ledger_index_correlation_id_idx').on(table.correlationId),
  ],
);

export const idempotencyKeys = pgTable(
  'idempotency_keys',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    subject: text('subject').notNull(),
    key: text('key').notNull(),
    result: jsonb('result'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  },
  (table) => [
    // Scoped to (subject, site) per prd.md EMCP-044 — a repeat key returns
    // the prior result rather than re-executing.
    uniqueIndex('idempotency_keys_subject_site_key_idx').on(table.subject, table.siteId, table.key),
    index('idempotency_keys_site_id_idx').on(table.siteId),
  ],
);

export const approvalTokens = pgTable(
  'approval_tokens',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    postId: integer('post_id').notNull(),
    // Bound to (site, post_id, content_hash) — solution.md's publish_draft
    // decision.
    contentHash: text('content_hash').notNull(),
    // Hash of the token, not the token itself — never store a bearer
    // secret in plaintext, even in our own database.
    tokenHash: text('token_hash').notNull(),
    used: boolean('used').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  },
  (table) => [
    uniqueIndex('approval_tokens_token_hash_idx').on(table.tokenHash),
    index('approval_tokens_site_id_idx').on(table.siteId),
  ],
);

export const previewNonces = pgTable(
  'preview_nonces',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    postId: integer('post_id').notNull(),
    // Signed, single-use, non-enumerable (Blueprints.md §6.5) — same
    // hash-not-plaintext rule as approval_tokens.
    tokenHash: text('token_hash').notNull(),
    used: boolean('used').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  },
  (table) => [
    uniqueIndex('preview_nonces_token_hash_idx').on(table.tokenHash),
    index('preview_nonces_site_id_idx').on(table.siteId),
  ],
);
